### PR TITLE
Add toInt

### PR DESCRIPTION
**Pull request by radrow**
Regarding #30 but didn't think of it very much. Seems to work.

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you for your contribution!

Not sure if that's the best way to implement it (convert to Number first). Does it fail in the right cases?
In general, I think it would be a good idea to add some tests. And test for edge cases, in particular.

**Comment by radrow** [comment]
yeah, will do. If it fails to work as expected I'll do it through FFI

**Comment by radrow** [comment]
Could you check it now? @sharkdp

**Review by sharkdp — APPROVED** [review]
Looks great.

Waiting for the ([now ultraslow](https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works)) Travis build to finish.

**Comment by radrow** [comment]
Is the CI properly set?

**Comment by sharkdp** [comment]
Currently fails with
```
* Build successful.
* Running tests...
* ERROR: Entry point module (Test.Main) not found.
The command "npm run -s build" exited with 1.
0.47s$ bower install
The command "bower install" exited with 0.
0.22s$ npm -s test
The command "npm -s test" exited with 1.
```

Not related to your PR. Haven't updated the CI pipeline in a long time :-/. It would be great to fix this first, but I can also merge your changes and release a new version, if you need that for another project.

**Comment by radrow** [comment]
Tests are passing on my side. This is not urgent as the fix was really simple so I can workaround it in my project by redefining that function.

**Comment by sharkdp** [comment]
I migrated the CI pipeline to GitHub Actions. Builds succeed now. Thank you!

**Pull request merged**
